FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV OTLP_ENDPOINT=http://jaeger:4318
EXPOSE 8083
CMD ["uvicorn", "poc3_security.api:app", "--host", "0.0.0.0", "--port", "8083"]
