name: MediSupply POCs CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-pocs:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: [5432:5432]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports: [6379:6379]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run POC1 API
        run: nohup uvicorn poc1_inventory.api:app --port 8080 &
      - name: Wait for API
        run: sleep 5
      - name: Test Inventory API with k6
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/k6_inventory.js
      - name: Test Routing API
        run: echo "TODO: add container-based test for POC2"
